version: "3.1"
services:

    mysql-faq:
      image: mysql:latest
      command: --default-authentication-plugin=mysql_native_password
      restart: unless-stopped
      container_name: mysql-faq
      tty: true
      ports:
        - "3306:3306"
      volumes:
        - ./session:/var/lib/mysql
      #      - ./insidex_crm.sql:/docker-entrypoint-initdb.d/insidex_crm.sql
      environment:
        - MYSQL_USER=${DB_USERNAME}
        - MYSQL_PASSWORD=${DB_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        - MYSQL_DATABASE=${DB_DATABASE}

    phpmyadmin-faq:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
        - PMA_ARBITRARY=1
      restart: always
      ports:
        - 8080:80
      volumes:
        - /sessions
      depends_on:
        - mysql-faq



    webserver-faq:
      image: nginx:alpine
      container_name: webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8000:80"
      depends_on:
        - php-fpm-faq
        - mysql-faq

    php-fpm-faq:
      build: docker
      container_name: php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
      depends_on:
        - mysql-faq

    node-faq:
      image: node:alpine
      container_name: node
      working_dir: /application
      volumes:
        - .:/application
      tty: true

